name: ttt_engine
description: Tic-Tac-Toe Engine
version: 1.0.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  built_value: ^8.4.4
  built_collection: ^5.1.1
  rxdart: ^0.27.7
  uuid: ^3.0.7

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.2
  build_runner: ^2.3.3
  built_value_generator: ^8.4.4
